CREATE DATABASE IF NOT EXISTS books_db;

USE books_db;

CREATE TABLE IF NOT EXISTS books (
  id INT AUTO_INCREMENT PRIMARY KEY,
  titolo VARCHAR(255) NOT NULL,
  autore VARCHAR(255) NOT NULL,
  anno INT NOT NULL,
  genere VARCHAR(100) NOT NULL
);
